export const ACTIONS = {
  dismiss: 'DISMISS',
  notify: 'NOTIFY',
  appLoading: 'APP_LOADING',
  appLoaded: 'APP_LOADED',
  sprintCreated: 'SPRINT_CREATED',
  sprintFilter: 'SPRINT_FILTER',
  sprintFilterShowAll: 'SPRINT_FILTER_SHOWALL',
  userCreated: 'USER_CREATED',
  sprintReceived: 'SPRINT_RECEIVED',
  sprintStarted: 'SPRINT_STARTED',
  boardReceived: 'BOARD_RECEIVED',
  boardCreated: 'BOARD_CREATED',
  userReceived: 'USER_RECEIVED',
  taskReceived: 'TASK_RECEIVED',
  taskCreated: 'TASK_CREATED',
  taskUpdated: 'TASK_UPDATED',
  taskDetach: 'TASK_DETACH',
  taskAttach: 'TASK_ATTACH',
  boardUpdated: 'BOARD_UPDATED',
  boardSelect: 'BOARD_SELECT'
}
