export const ICONS = {
  toDo: 'up-square-o',
  inProgress: 'right-square-o',
  onHold: 'down-square-o',
  resolved: 'minus-square-o',
  done: 'check-square-o',
  boardIndex: 'compass',
  task: 'bars',
  board: 'schedule',
  sprint: 'rocket',
  backlog: 'inbox',
  save: 'save',
  admin: 'laptop',
  user: 'customer-service',
  team: 'customer-service',
  incident: 'exception',
  epic: 'trophy',
  meeting: 'flag',
  menu: 'appstore',
  logo: 'swap',
  calendar: 'calendar'
}
